cars_index:
    path: /
    controller: App\Controller\CarController::index
    methods: [GET]

cars_add:
    path: /cars/add
    controller: App\Controller\CarController::add
    methods: [POST]

cars_edit:
    path: /cars/edit/{id}
    controller: App\Controller\CarController::edit
    methods: [POST]

cars_delete:
    path: /cars/delete/{id}
    controller: App\Controller\CarController::delete
    methods: [POST]

cars_truncate:
    path: /cars/truncate
    controller: App\Controller\CarController::truncate
    methods: [POST]